version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:80'
    volumes:
      - ./:/var/www/html/

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8083:80'
    environment:
      - PMA_ARBITRARY=1
